name: Build, Test, and Deploy to Azure

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    # Ejecuta en el último Ubuntu disponible
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configura la versión de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'  # Cambia esto si necesitas otra versión
          cache: 'npm'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar el build del proyecto (si corresponde)
      - name: Build project
        run: npm run build --if-present  # Si tu proyecto tiene un proceso de build

      # Paso 5: Ejecutar las pruebas
      - name: Run tests
        run: npm test

  deploy:
    # Este trabajo depende de que el trabajo anterior de Build y Test haya sido exitoso
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      # Paso 6: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 7: Desplegar al servidor (puedes ajustar este paso según tu despliegue)
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/project
            git pull origin master
            npm install --production
            npm run build --if-present
            pm2 restart all  # Si usas pm2 para gestionar tu servidor de Node.js
